repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      - id: poetry-export
      - id: poetry-export
        args : ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--with", "dev"]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.0'
    hooks:
    -   id: autopep8
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: ["--in-place", "--pre-summary-newline"]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: isort
        args: ["-l 119", "--conda-env", "./venv"]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: [ "bandit[toml]" ]